sudo: required
services:
  - docker

before_install:
  - docker build -t vgeorgework/flaskapp .

script:
  - docker run -d vgeorgework/flaskapp 

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vgeorgework/flaskapp
