apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials-flask
  annotations:
    avp.kubernetes.io/path: "internal/database/flaskapp/config"
type: Opaque
stringData:
 username: <username>
 password: <password>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf-flask
data:
 host: mysql
 name: TEST
