apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  annotations:
    avp.kubernetes.io/path: "internal/database/flaskapp/config"
type: Opaque
stringData:
 username: <username>
 password: <password>
---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
  annotations:
  avp.kubernetes.io/path: "internal/database/flaskapp/config"
stringdata:
 rootpassword: <rootpassword>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf
data:
 host: mysql
 name: test

